apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsocket-broker
  namespace: rsocket
  labels:
    app: rsocket-broker
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: rsocket-broker
      labels:
        app: rsocket-broker
    spec:
      containers:
        - name: rsocket-broker
          image: linuxchina/alibaba-rsocket-broker:{{.Values.broker.version}}-k8s
          ports:
            - containerPort: 9997
            - containerPort: 9998
            - containerPort: 9999
          imagePullPolicy: IfNotPresent
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9997
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9997
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 30" ]
      restartPolicy: Always
  selector:
    matchLabels:
      app: rsocket-broker