{{ if .Values.broker.secure }}
kind: Secret
apiVersion: v1
metadata:
  name: rsocket-broker-secrets
  namespace: rsocket
type: Opaque
data:
  {{- if ne .Values.broker.jwtRSAPubKey ""}}
  jwtRSAPubKey: >-
    {{ .Files.Get .Values.broker.jwtRSAPubKey | b64enc }}
  {{- end }}
  {{- if ne .Values.broker.tlsKeyStore ""}}
  tlsKeyStore: >-
    {{ .Files.Get .Values.broker.tlsKeyStore | b64enc }}
  {{- end }}
{{ end }}
