apiVersion: v1
kind: Service
metadata:
  name: rsocket-broker
  namespace: rsocket
spec:
  ports:
    - name: http
      port: 9998
      targetPort: 9998
      protocol: TCP
    - name: rsocket
      port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app: rsocket-broker